$(document).ready(function() {
  $("#image2").mouseover(function(){
  $("#drug").show();
  });
  $("#image2").mouseout(function(){
  $("#drug").hide();
  });

  $("#image").mouseover(function(){
  $("#forgot").show();
  });
  $("#image").mouseout(function(){
  $("#forgot").hide();
  });

  $("#image3").mouseover(function(){
  $("#see").show();
  });
  $("#image3").mouseout(function(){
  $("#see").hide();
  });

    $("#image4").mouseover(function(){
    $("#presis").show();
    });
    $("#image4").mouseout(function(){
    $("#presis").hide();
    });

    $("#image5").mouseover(function(){
    $("#eyes").show();
    });
    $("#image5").mouseout(function(){
    $("#eyes").hide();
    });

    $("#image6").mouseover(function(){
    $("#nations").show();
    });
    $("#image6").mouseout(function(){
    $("#nations").hide();
    });

    $("#image7").mouseover(function(){
    $("#neo").show();
    });
    $("#image7").mouseout(function(){
    $("#neo").hide();
    });

    $("#image8").mouseover(function(){
    $("#heres").show();
    });
    $("#image8").mouseout(function(){
    $("#heres").hide();
    });

    $("#image9").mouseover(function(){
    $("#coding").show();
    });
    $("#image9").mouseout(function(){
    $("#coding").hide();
    });

    $("#image10").mouseover(function(){
    $("#ae").show();
    });
    $("#image10").mouseout(function(){
    $("#ae").hide();
    });

    $("#image11").mouseover(function(){
    $("#maps").show();
    });
    $("#image11").mouseout(function(){
    $("#maps").hide();
    });
    $("#image12").mouseover(function(){
    $("#tesis").show();
    });
    $("#image12").mouseout(function(){
    $("#tesis").hide();
    });
    $("#image13").mouseover(function(){
    $("#mapacampaña").show();
    });
    $("#image13").mouseout(function(){
    $("#mapacampaña").hide();
    });
    $("#image14").mouseover(function(){
    $("#fuegos").show();
    });
    $("#image14").mouseout(function(){
    $("#fuegos").hide();
    });
    $("#image15").mouseover(function(){
    $("#nobel").show();
    });
    $("#image15").mouseout(function(){
    $("#nobel").hide();
    });
    $("#image16").mouseover(function(){
    $("#volcan").show();
    });
    $("#image16").mouseout(function(){
    $("#volcan").hide();
    });
    $("#image17").mouseover(function(){
    $("#ilustraciones").show();
    });
    $("#image17").mouseout(function(){
    $("#ilustraciones").hide();
    });
    $("#image18").mouseover(function(){
    $("#resultados").show();
    });
    $("#image18").mouseout(function(){
    $("#resultados").hide();
    });
    $("#image19").mouseover(function(){
    $("#guerra").show();
    });
    $("#image19").mouseout(function(){
    $("#guerra").hide();
    });
    $("#image20").mouseover(function(){
    $("#coches").show();
    });
    $("#image20").mouseout(function(){
    $("#coches").hide();
    });
    $("#image21").mouseover(function(){
    $("#racismo").show();
    });
    $("#image21").mouseout(function(){
    $("#racismo").hide();
    });
    $("#image22").mouseover(function(){
    $("#covid").show();
    });
    $("#image22").mouseout(function(){
    $("#covid").hide();
    });
    $("#image23").mouseover(function(){
    $("#calles").show();
    });
    $("#image23").mouseout(function(){
    $("#calles").hide();
    });
});
